- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
- app/policies/application_policy.rb
- app/policies/dish_policy.rb
- app/policies/kitchen_policy.rb
- app/policies/location_policy.rb
- app/policies/order_policy.rb
- app/policies/plan_policy.rb
- test/policies/dish_policy_test.rb
- test/policies/kitchen_policy_test.rb
- test/policies/location_policy_test.rb
- test/policies/order_policy_test.rb
- test/policies/plan_policy_test.rb
> finished pundit

- app/controllers/pages_controller.rb
- app/views/pages/uikit_kid.html.erb
- config/routes.rb
> finished uikit_kid route controller and view

- app/controllers/kitchens_controller.rb
- app/models/plan.rb
- app/views/kitchens/new.html.erb
- app/views/kitchens/show.html.erb
- app/views/pages/home.html.erb
- config/routes.rb
- test/controllers/kitchens_controller_test.rb
> fin kitchens controller and simple view

- app/assets/stylesheets/components/_home_card.scss
- app/views/pages/uikit_kid.html.erb
> double checked home-card

- app/assets/stylesheets/components/_index.scss
- app/views/pages/uikit_kid.html.erb
> add button in home-card

- app/views/pages/uikit_kid.html.erb
added tag comment in index-card
> added tag comment.Backend syntax should be added later in p tag

- app/assets/stylesheets/components/_button.scss
- app/assets/stylesheets/components/_searchbar.scss
- app/views/pages/uikit_kid.html.erb
created search bar with placeholder
> created search bar

- app/controllers/orders_controller.rb
- app/views/orders/index.html.erb
- app/views/pages/home.html.erb
- db/seeds.rb
> fixed view&controller of my order page

- app/views/kitchens/show.html.erb
- app/views/pages/home.html.erb
- app/views/plans/show.html.erb
@m-nath 
@HuishuJia @sho-hei-sd
> fixed most of views

- app/assets/stylesheets/components/_button.scss
- app/assets/stylesheets/components/_navbar.scss
- app/views/pages/uikit_kid.html.erb
- app/views/shared/_navbar.html.erb
____Done____
- Navbar order & link
- button conflict solved
____To Do____
- Navbar search button & location button functionality to be done
> Navbar link & order

- app/assets/stylesheets/components/_box.scss
- app/assets/stylesheets/components/_index.scss
- app/views/pages/uikit_kid.html.erb
> created empty box

- app/views/pages/uikit_kid.html.erb
created a plan, but need to work on dropdown.
> created plan dropdown

- app/assets/stylesheets/components/_button.scss
- app/views/devise/sessions/new.html.erb
> make it beautiful. chnange width

- app/views/devise/registrations/new.html.erb
> customize sign-up page. make it center

- app/assets/stylesheets/components/_plan_card.scss
> changed image size to 150x150 pixel

- app/assets/stylesheets/components/_box.scss
> changed size of box

- app/views/pages/uikit_kid.html.erb
just made <p> visible for the reference in the future.
In <p>, tag will be embedded in the future.
> created tag for plan-card and long-card

- app/assets/stylesheets/components/_long_card.scss
- app/assets/stylesheets/components/_meal_card.scss
- app/views/pages/uikit_kid.html.erb
> fixed individual meal card

- app/assets/stylesheets/components/_plancard.scss
- app/views/pages/uikit_kid.html.erb
> Responsive for weekly plan

- app/assets/stylesheets/components/_index_card.scss
- app/assets/stylesheets/components/_navbar.scss
- app/views/pages/home.html.erb
> avatar fix and navbar fix

- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/pages/_home.scss
- app/views/layouts/application.html.erb
- app/views/shared/_navbar.html.erb
- app/views/shared/_plancard_index.html.erb
navbar position fixed and added user name
> navbar position fixed and added user name

- app/assets/stylesheets/components/_meal_card.scss
- app/views/kitchens/show.html.erb
- app/views/pages/uikit_kid.html.erb
- app/views/shared/_fivedays_card.html.erb
- app/views/shared/_plancard.html.erb
> created partial 5 days card

- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
> style edit page'

- app/assets/stylesheets/components/_meal_card.scss
- app/assets/stylesheets/components/_plan_card.scss
- app/assets/stylesheets/components/_plancard.scss
- app/views/kitchens/show.html.erb
- db/schema.rb
> responsive design

- db/seeds.rb
> sorry real fixed seed

- app/views/chat_rooms/_show.html.erb
- app/views/orders/index.html.erb
- db/migrate/20190828023403_add_video_to_kitchens.rb
- db/schema.rb
- db/seeds.rb
> fixed seeds and my order page
